/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnilistUser {
        "hideAnime": boolean;
        "hideManga": boolean;
        "useDarkMode": boolean;
        "username": string;
    }
}
declare global {
    interface HTMLAnilistUserElement extends Components.AnilistUser, HTMLStencilElement {
    }
    var HTMLAnilistUserElement: {
        prototype: HTMLAnilistUserElement;
        new (): HTMLAnilistUserElement;
    };
    interface HTMLElementTagNameMap {
        "anilist-user": HTMLAnilistUserElement;
    }
}
declare namespace LocalJSX {
    interface AnilistUser {
        "hideAnime"?: boolean;
        "hideManga"?: boolean;
        "useDarkMode"?: boolean;
        "username"?: string;
    }
    interface IntrinsicElements {
        "anilist-user": AnilistUser;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "anilist-user": LocalJSX.AnilistUser & JSXBase.HTMLAttributes<HTMLAnilistUserElement>;
        }
    }
}
